services:
    postgres:
        image: postgres:alpine
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        build: .
        command: pipenv run python manage.py runserver "0.0.0.0:8000"
        depends_on:
            - postgres
        env_file:
            - .env
        environment:
            WORKON_HOME: /root/.virtualenvs
            PIPENV_CACHE_DIR: /root/.cache/pipenv
        working_dir: /app
        volumes:
            - .:/app
            - pipenv_cache:/root/.cache/pipenv
            - pipenv_venv:/root/.virtualenvs
        ports:
            - "8000:8000"

volumes:
    postgres_data:
    pipenv_cache:
    pipenv_venv:
