import pytest
from playwright.sync_api import Page


@pytest.fixture(scope="session")
def browser_context_args(browser_context_args, playwright):
    return {**playwright.devices["Galaxy S9+"]}


def test_create_a_new_court(page: Page) -> None:
    page.goto("http://localhost:8000/courts/")
    page.get_by_label("Toggle navigation").click()
    page.get_by_role("link", name="Entrar").click()
    page.get_by_role("link", name="Cadastrar").click()
    page.get_by_label("Primeiro nome").click()
    page.get_by_label("Primeiro nome").fill("ana")
    page.get_by_label("Primeiro nome").press("Tab")
    page.get_by_label("Sobrenome").fill("sena")
    page.get_by_label("Sobrenome").press("Tab")
    page.get_by_label("Email").fill("a@sena.com")
    page.get_by_label("Email").press("Tab")
    page.get_by_label("Usuário").fill("ana")
    page.get_by_label("Usuário").press("Tab")
    page.get_by_label("Senha", exact=True).fill("ana")
    page.get_by_label("Senha", exact=True).press("Tab")
    page.get_by_label("Confirmar senha").fill("ana")
    page.get_by_label("Confirmar senha").press("Enter")
    page.get_by_label("Toggle navigation").click()
    page.get_by_role("link", name="Minhas quadras").click()
    page.get_by_role("link", name="Adicionar quadra").click()
    page.get_by_label("Name").click()
    page.get_by_label("Name").fill("Falc")
    page.get_by_label("Description").click()
    page.get_by_label("Description").fill("Maior quadra do mundo")
    page.get_by_label("Zip code").click()
    page.get_by_label("Zip code").fill("3214")
    page.get_by_label("Street").click()
    page.get_by_label("Street").fill("R. Dos Bobos")
    page.get_by_label("Number").click()
    page.get_by_label("Number").fill("0")
    page.get_by_label("Neighborhood").click()
    page.get_by_label("Neighborhood").fill("Jardim Ali")
    page.get_by_label("City").click()
    page.get_by_label("City").fill("Aqui")
    page.get_by_label("State").click()
    page.get_by_label("State").fill("La")
    page.get_by_label("Facilities").click()
    page.get_by_label("Facilities").fill("bar")
    page.get_by_label("Availability weeks").click()
    page.get_by_label("Availability weeks").fill("seg")
    page.get_by_label("Availability times").click()
    page.get_by_label("Availability times").fill("9h")
    page.get_by_label("Single price").click()
    page.get_by_label("Single price").fill("30")
    page.get_by_label("Monthly price").click()
    page.get_by_label("Monthly price").fill("100")
    page.get_by_role("button", name="Cadastrar").click()
